OPTIONS (SKIP=1)
LOAD DATA
INFILE 'D:\DATA WARE HOUSE\apex-finance\backend\data\dim_account.csv'
APPEND
INTO TABLE DIM_ACCOUNT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  account_id INTEGER EXTERNAL,
  account_type CHAR(100)
)

