OPTIONS (SKIP=1)
LOAD DATA
INFILE 'D:\DATA WARE HOUSE\apex-finance\backend\data\dim_category.csv'
APPEND
INTO TABLE DIM_CATEGORY
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  category_id INTEGER EXTERNAL,
  category_name CHAR(100)
)

