OPTIONS (SKIP=1)
LOAD DATA
INFILE 'D:\DATA WARE HOUSE\apex-finance\backend\data\dim_date.csv'
APPEND
INTO TABLE DIM_DATE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  date_id INTEGER EXTERNAL,
  full_date DATE "YYYY-MM-DD",
  day INTEGER EXTERNAL,
  month INTEGER EXTERNAL,
  year INTEGER EXTERNAL
)

