OPTIONS (SKIP=1)
LOAD DATA
INFILE 'D:\DATA WARE HOUSE\apex-finance\backend\data\fact_budget.csv'
APPEND
INTO TABLE FACT_BUDGET
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  budget_id INTEGER EXTERNAL,
  category_id INTEGER EXTERNAL,
  month DATE "YYYY-MM-DD",
  budget_amount DECIMAL EXTERNAL
)

