OPTIONS (SKIP=1, ROWS=5000, BINDSIZE=1048576, READSIZE=1048576)
LOAD DATA
INFILE 'D:\DATA WARE HOUSE\apex-finance\backend\data\fact_transactions.csv'
APPEND
INTO TABLE FACT_TRANSACTIONS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  transaction_id INTEGER EXTERNAL,
  date_id INTEGER EXTERNAL,
  category_id INTEGER EXTERNAL,
  account_id INTEGER EXTERNAL,
  amount DECIMAL EXTERNAL
)

